<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ttl</string>
		<string>turtle</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~T</string>
	<key>name</key>
	<string>Turtle</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.turtle</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.turtle</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.turtle</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>.*</string>
					<key>name</key>
					<string>constant.character.escape.turtle</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^@prefix\s</string>
			<key>end</key>
			<string>\s*.$</string>
			<key>name</key>
			<string>meta.directive.prefix.turtle</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>([\w\-]*:)</string>
					<key>name</key>
					<string>constant.other.prefix.turtle</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#IRI</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#spo_stmt</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.turtle</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(#).*$\n?</string>
			<key>name</key>
			<string>comment.line.number-sign.turtle</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>IRI</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.entity.begin.turtle</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.entity.end.turtle</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\&lt;).+(\&gt;)</string>
			<key>name</key>
			<string>entity.name.type.iri.turtle</string>
		</dict>
		<key>blank_node</key>
		<dict>
			<key>begin</key>
			<string>(\[)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.bnode.open</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.bnode.close</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.triple.node.blank</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#po_stmt</string>
				</dict>
			</array>
		</dict>
		<key>collection_short</key>
		<dict>
			<key>begin</key>
			<string>(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.collection.open</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.collection.close</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.triple.node.collection.short</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#literal</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#typed_literal</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#blank_node</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#collection_short</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#IRI</string>
				</dict>
			</array>
		</dict>
		<key>literal</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.turtle</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.turtle</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(")[^"\\]*(?:\\.[^"\\]*)*(")(?!\^\^)</string>
			<key>name</key>
			<string>string.quoted.double.turtle</string>
		</dict>
		<key>po_stmt</key>
		<dict>
			<key>begin</key>
			<string>[\b\s]?([\w\-]*:)([\w]+)[\b\s]?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.other.prefix.turtle</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.turtle</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(;|$)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.triple.terminator.turtle</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.triple.stmt</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#sp_expr</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#literal</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#typed_literal</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#blank_node</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#collection_short</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#IRI</string>
				</dict>
			</array>
		</dict>
		<key>sp_expr</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.other.prefix.turtle</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.turtle</string>
				</dict>
			</dict>
			<key>match</key>
			<string>[\b\s]?([\w\-]*:)([\w]+)[\b\s]?</string>
		</dict>
		<key>spo_stmt</key>
		<dict>
			<key>begin</key>
			<string>\s*([\w\-]*:)([\w]+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.other.prefix.turtle</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.turtle</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\.)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.triple.terminator</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.triple.spo</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#po_stmt</string>
				</dict>
			</array>
		</dict>
		<key>typed_literal</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.turtle</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.turtle</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.turtle</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>storage.type.datatype.turtle</string>
				</dict>
			</dict>
			<key>match</key>
			<string>((")[^"\\]*(?:\\.[^"\\]*)*("))(\^\^[\w^:]*:[\w\-]+)</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.turtle</string>
	<key>uuid</key>
	<string>3EB8C7E3-67FD-41FF-A257-6466443C6503</string>
</dict>
</plist>
